### ISSUE TITLE
Consider replacing kitsu.js with kitsu

### ISSUE THREAD

**Issue by wopian** [HasanBrandsXD/GalaxyBOT#14]
[kitsu.js](https://yarnpkg.com/en/package/kitsu.js) is deprecated in favour of the more feature complete [kitsu](https://yarnpkg.com/en/package/kitsu) package that is fully JSON-API compliant.

Search is implemented with:

```js
import Kitsu from 'kitsu'

const api = new Kitsu()

api.fetch('anime', {
  filter: { 
    text: 'Cowboy Bebop'
  }
})
```

**Comment by brands-xd** [comment]
Sure, I don't have time to edit anime. I'll give the task to the developers, thanks!
