### ISSUE TITLE
Galaxy turns off & online instantly

### ISSUE THREAD

**Issue by Wendy009** [HasanBrandsXD/GalaxyBOT#3]
When running the command &unban Galaxy turns off & turns on instantly, I can tell this by looking at the member list of my server.

**Comment by MayaDIS** [comment]
Hey @Wendy009!
We are completely aware of our unban command, as it is, pretty much broken. I have fixed this after monitering this command a thousand times, it should work completely fine now.

**Comment by MayaDIS** [comment]
If the issue is still encountered, please DM me on Discord (Maya#9410)
