### ISSUE TITLE
Does not play music

### ISSUE THREAD

**Issue by Wendy009** [HasanBrandsXD/GalaxyBOT#4]
When adding 10+ songs to the queue, music stops playing instantly.  After 6 or 10 seconds it starts skipping music.

**Comment by Wendy009** [comment]
please fix this

**Comment by MayaDIS** [comment]
Hey there!
Thanks for reporting that savage issue! This is a bug, and we completely appreciate what you have reported! This issue will be marked as a bug.

@HasanBrandsXD

**Comment by brands-xd** [comment]
As Maya said, this is a bug. I'll post updates on this.

**Comment by brands-xd** [comment]
Fixed this, if this is still encountered please DM me (HasanBrandsXD#4120)
