### ISSUE TITLE
Action commands

### ISSUE THREAD

**Issue by RubyBubbie** [HasanBrandsXD/GalaxyBOT#5]
When I type any of the action commands without mentioning someone like `&slap` (no user / id) it says Bubbie <3 (my discord username) slapped null

**Comment by brands-xd** [comment]
Yep, I'm pretty much aware of this issue, but I'm, I guess, to busy at the moment to fix this, I'll set a developer to look on this.

**Comment by brands-xd** [comment]
Can't fix, closing issue.
