### ISSUE TITLE
The bot does not play music

### ISSUE THREAD

**Issue by ArberSupremo** [HasanBrandsXD/GalaxyBOT#7]

**Comment by brands-xd** [comment]
Sorry, can you be a little more specific?

**Comment by brands-xd** [comment]
If you do not know already you have to add a song to the queue by `&add <yt link>` then type `&play` which will play songs from the queue.

FYI, restarted Music maybe it'll work now, please let me know.

**Comment by brands-xd** [comment]
No reply since past 48 hours, closing issue.
